# Tested cross compiling with MinGW compiler on Linux - x86_64 and i686 target architectures

CPPFLAGS = -O2 -W -Wall -Wextra -std=c++20
LIBRARIES = -lws2_32

all: netmount-server.exe

netmount-server.exe: netmount-server.cpp fs.cpp fs.hpp udp_socket_win.cpp udp_socket.hpp utils.hpp ../shared/dos.h ../shared/drvproto.h
	$(CXX) $(CPPFLAGS) netmount-server.cpp fs.cpp udp_socket_win.cpp $(LIBRARIES) -o $@

clean:
	rm -f netmount-server.exe
